[project]
name = "hackathonsia2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "lmstudio>=1.5.0",
    "openai>=2.21.0",
    "pandas>=3.0.1",
    "pydantic>=2.12.5",
]
